version: 2.0.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: Any CPU
clone_folder: C:\TheCrafters001\Build\TF2-Server-Manager\src\bin
before_build:
- ps: nuget restore 'C:\TheCrafters001\Build\TF2-Server-Manager\src\bin\src\TF2 Server Manager.sln'
build:
  verbosity: minimal